### ISSUE TITLE
Is this abandoned, right?

### ISSUE THREAD

**Issue by frederikhors** [zeebo/drpc-rs#1]
Is this abandoned, right?

**Comment by zeebo** [comment]
What do you mean by abandoned? I'm not currently working on it, but I'm happy to work on it again if there's interest, especially if someone has some Rust domain expertise to share.

**Comment by frederikhors** [comment]
I mean is not an active project on which I can rely on for production instead of - say - tonic grpc-web.

Anyway thanks for the answer.

**Comment by zeebo** [comment]
Indeed, it is not in a usable state for production yet.
